export const sampleArticles = [
    {
        "type_of": "article",
        "id": 2244746,
        "title": "Meme Monday",
        "description": "Meme Monday!  Today's cover image comes from last week's thread.  DEV is an inclusive space! Humor in...",
        "readable_publish_date": "Jan 27",
        "slug": "meme-monday-419k",
        "path": "/ben/meme-monday-419k",
        "url": "https://dev.to/ben/meme-monday-419k",
        "comments_count": 43,
        "public_reactions_count": 97,
        "collection_id": null,
        "published_timestamp": "2025-01-27T13:51:32Z",
        "language": "en",
        "subforem_id": 1,
        "positive_reactions_count": 97,
        "cover_image": "https://media2.dev.to/dynamic/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fwqwnmrly77dmyks11ow3.png",
        "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fwqwnmrly77dmyks11ow3.png",
        "canonical_url": "https://dev.to/ben/meme-monday-419k",
        "created_at": "2025-01-27T13:51:33Z",
        "edited_at": null,
        "crossposted_at": null,
        "published_at": "2025-01-27T13:51:32Z",
        "last_comment_at": "2025-01-28T14:26:27Z",
        "reading_time_minutes": 1,
        "tag_list": [
            "discuss",
            "watercooler",
            "jokes"
        ],
        "tags": "discuss, watercooler, jokes",
        "user": {
            "name": "Ben Halpern",
            "username": "ben",
            "twitter_username": "bendhalpern",
            "github_username": "benhalpern",
            "user_id": 1,
            "website_url": "http://benhalpern.com",
            "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F1%2Ff451a206-11c8-4e3d-8936-143d0a7e65bb.png",
            "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F1%2Ff451a206-11c8-4e3d-8936-143d0a7e65bb.png"
        },
        "flare_tag": {
            "name": "discuss",
            "bg_color_hex": "#71EA8B",
            "text_color_hex": "#FFFFFF"
        }
    },
    {
        "type_of": "article",
        "id": 2246590,
        "title": "Identify Unknowns, Weaknesses, and Risks in AI",
        "description": "There's a lot that can go wrong with AI. Let's talk about how to minimize that risk.",
        "readable_publish_date": "Jan 28",
        "slug": "identify-unknowns-weaknesses-and-risks-in-ai-1gi6",
        "path": "/leading-edje/identify-unknowns-weaknesses-and-risks-in-ai-1gi6",
        "url": "https://dev.to/leading-edje/identify-unknowns-weaknesses-and-risks-in-ai-1gi6",
        "comments_count": 0,
        "public_reactions_count": 8,
        "collection_id": 29583,
        "published_timestamp": "2025-01-28T14:20:04Z",
        "language": "en",
        "subforem_id": 1,
        "positive_reactions_count": 8,
        "cover_image": "https://media2.dev.to/dynamic/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Faj21tvw0e20cdg44g9f4.jpg",
        "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Faj21tvw0e20cdg44g9f4.jpg",
        "canonical_url": "https://blog.leadingedje.com/post/aiprototyping/identifyingairisks.html",
        "created_at": "2025-01-28T14:20:05Z",
        "edited_at": "2025-01-28T14:21:00Z",
        "crossposted_at": null,
        "published_at": "2025-01-28T14:20:04Z",
        "last_comment_at": "2025-01-28T14:20:04Z",
        "reading_time_minutes": 7,
        "tag_list": [
            "ai",
            "projects",
            "projectmanagement",
            "riskmanagement"
        ],
        "tags": "ai, projects, projectmanagement, riskmanagement",
        "user": {
            "name": "Matt Eland",
            "username": "integerman",
            "twitter_username": "integerman",
            "github_username": "IntegerMan",
            "user_id": 71302,
            "website_url": "https://matteland.dev",
            "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F71302%2F74cf3bad-1dea-411b-b68b-d34cbcedd625.jpg",
            "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F71302%2F74cf3bad-1dea-411b-b68b-d34cbcedd625.jpg"
        },
        "organization": {
            "name": "Leading EDJE",
            "username": "leading-edje",
            "slug": "leading-edje",
            "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F1988%2Fd7dc325f-e3e6-4445-8ec6-9353b07e365d.jpg",
            "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F1988%2Fd7dc325f-e3e6-4445-8ec6-9353b07e365d.jpg"
        }
    },
    {
        "type_of": "article",
        "id": 2244854,
        "title": "Attending Tech Conferences With a Toddler: A DevRel Mom’s Story",
        "description": "Introduction   My career didn't have to stop because I became a mother; if anything, my...",
        "readable_publish_date": "Jan 27",
        "slug": "attending-tech-conferences-with-a-toddler-a-devrel-moms-story-41np",
        "path": "/vonagedev/attending-tech-conferences-with-a-toddler-a-devrel-moms-story-41np",
        "url": "https://dev.to/vonagedev/attending-tech-conferences-with-a-toddler-a-devrel-moms-story-41np",
        "comments_count": 2,
        "public_reactions_count": 6,
        "collection_id": null,
        "published_timestamp": "2025-01-27T15:49:53Z",
        "language": "en",
        "subforem_id": 1,
        "positive_reactions_count": 6,
        "cover_image": "https://media2.dev.to/dynamic/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fkjphxlgwyb6yx7garwgx.png",
        "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fkjphxlgwyb6yx7garwgx.png",
        "canonical_url": "https://developer.vonage.com/en/blog/attending-tech-conferences-with-a-toddler-a-devrel-mom-s-story",
        "created_at": "2025-01-27T15:48:57Z",
        "edited_at": null,
        "crossposted_at": null,
        "published_at": "2025-01-27T15:49:53Z",
        "last_comment_at": "2025-01-27T22:17:19Z",
        "reading_time_minutes": 9,
        "tag_list": [
            "devrel"
        ],
        "tags": "devrel",
        "user": {
            "name": "Amanda Cavallaro",
            "username": "chibichibibr",
            "twitter_username": null,
            "github_username": "amdcavallaro",
            "user_id": 364684,
            "website_url": "https://www.amandacavallaro.com",
            "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F364684%2Ff3b063b2-f8fa-480d-acfc-1c876959a11b.jpg",
            "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F364684%2Ff3b063b2-f8fa-480d-acfc-1c876959a11b.jpg"
        },
        "organization": {
            "name": "Vonage",
            "username": "vonagedev",
            "slug": "vonagedev",
            "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F378%2F555ac53a-0535-46ae-8d35-c875f44eb774.jpg",
            "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F378%2F555ac53a-0535-46ae-8d35-c875f44eb774.jpg"
        }
    },
    {
        "type_of": "article",
        "id": 2240770,
        "title": "Responsible Innovation: Open Source Best Practices for Sustainable AI",
        "description": "Accelerate AI without sacrificing ethics. Discover red teaming, open source, and an AI Bill of Materials for secure, transparent AI development.",
        "readable_publish_date": "Jan 27",
        "slug": "responsible-innovation-open-source-best-practices-for-sustainable-ai-jei",
        "path": "/bekahhw/responsible-innovation-open-source-best-practices-for-sustainable-ai-jei",
        "url": "https://dev.to/bekahhw/responsible-innovation-open-source-best-practices-for-sustainable-ai-jei",
        "comments_count": 0,
        "public_reactions_count": 10,
        "collection_id": null,
        "published_timestamp": "2025-01-27T09:01:00Z",
        "language": "en",
        "subforem_id": 1,
        "positive_reactions_count": 10,
        "cover_image": "https://media2.dev.to/dynamic/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fyiway1jka1g9ww90dbgc.png",
        "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fyiway1jka1g9ww90dbgc.png",
        "canonical_url": "https://www.linuxfoundation.org/blog/responsible-innovation-open-source-best-practices-for-sustainable-ai",
        "created_at": "2025-01-25T19:34:43Z",
        "edited_at": null,
        "crossposted_at": null,
        "published_at": "2025-01-27T09:01:00Z",
        "last_comment_at": "2025-01-27T09:01:00Z",
        "reading_time_minutes": 6,
        "tag_list": [
            "ai"
        ],
        "tags": "ai",
        "user": {
            "name": "BekahHW",
            "username": "bekahhw",
            "twitter_username": "BekahHW",
            "github_username": "BekahHW",
            "user_id": 345658,
            "website_url": "https://bekahhw.com/",
            "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F345658%2Fa72b6b8b-b954-47fb-8919-ab380905f26b.jpg",
            "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F345658%2Fa72b6b8b-b954-47fb-8919-ab380905f26b.jpg"
        }
    },
    {
        "type_of": "article",
        "id": 2244750,
        "title": "Derpify.js – a tool for these trying times…",
        "description": "Derpify is a JavaScript method to randomly upper and lowercase letters",
        "readable_publish_date": "Jan 27",
        "slug": "derpifyjs-a-tool-for-these-trying-times-4gmg",
        "path": "/codepo8/derpifyjs-a-tool-for-these-trying-times-4gmg",
        "url": "https://dev.to/codepo8/derpifyjs-a-tool-for-these-trying-times-4gmg",
        "comments_count": 1,
        "public_reactions_count": 3,
        "collection_id": null,
        "published_timestamp": "2025-01-27T13:59:51Z",
        "language": "en",
        "subforem_id": 1,
        "positive_reactions_count": 3,
        "cover_image": "https://media2.dev.to/dynamic/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fafzz8qtnpe3i4rv6cpwp.png",
        "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fafzz8qtnpe3i4rv6cpwp.png",
        "canonical_url": "https://christianheilmann.com/2025/01/27/derpify-js-is-now-on-npm-and-github-a-tool-for-these-trying-times/",
        "created_at": "2025-01-27T13:57:59Z",
        "edited_at": "2025-01-27T14:50:32Z",
        "crossposted_at": null,
        "published_at": "2025-01-27T13:59:51Z",
        "last_comment_at": "2025-01-28T06:48:36Z",
        "reading_time_minutes": 1,
        "tag_list": [
            "derp",
            "javascript",
            "stringmanipulation"
        ],
        "tags": "derp, javascript, stringmanipulation",
        "user": {
            "name": "Christian Heilmann",
            "username": "codepo8",
            "twitter_username": "codepo8",
            "github_username": "codepo8",
            "user_id": 110884,
            "website_url": "https://christianheilmann.com",
            "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F110884%2Fc4807448-b7fe-4d8d-ba13-a3ec4c97b377.jpeg",
            "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F110884%2Fc4807448-b7fe-4d8d-ba13-a3ec4c97b377.jpeg"
        }
    },
    {
        "type_of": "article",
        "id": 2244217,
        "title": "How to Use Deepseek API and Enable Streaming Output for Debugging",
        "description": "Login to Deepseek Open Platform   First, log in to the Deepseek Open Platform to obtain the...",
        "readable_publish_date": "Jan 27",
        "slug": "how-to-use-deepseek-api-and-enable-streaming-output-for-debugging-1ah9",
        "path": "/auden/how-to-use-deepseek-api-and-enable-streaming-output-for-debugging-1ah9",
        "url": "https://dev.to/auden/how-to-use-deepseek-api-and-enable-streaming-output-for-debugging-1ah9",
        "comments_count": 5,
        "public_reactions_count": 82,
        "collection_id": null,
        "published_timestamp": "2025-01-27T10:38:22Z",
        "language": "en",
        "subforem_id": 1,
        "positive_reactions_count": 82,
        "cover_image": "https://media2.dev.to/dynamic/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2F2fo7f9dilbl4g7o5pw1v.png",
        "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2F2fo7f9dilbl4g7o5pw1v.png",
        "canonical_url": "https://dev.to/auden/how-to-use-deepseek-api-and-enable-streaming-output-for-debugging-1ah9",
        "created_at": "2025-01-27T10:38:23Z",
        "edited_at": null,
        "crossposted_at": null,
        "published_at": "2025-01-27T10:38:22Z",
        "last_comment_at": "2025-01-28T14:27:51Z",
        "reading_time_minutes": 3,
        "tag_list": [
            "ai",
            "deepseek",
            "programming",
            "api"
        ],
        "tags": "ai, deepseek, programming, api",
        "user": {
            "name": "Auden",
            "username": "auden",
            "twitter_username": null,
            "github_username": "ringlxs",
            "user_id": 1410047,
            "website_url": null,
            "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F1410047%2Fe5c7109b-1424-4025-8170-7b59ad08f6f3.png",
            "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F1410047%2Fe5c7109b-1424-4025-8170-7b59ad08f6f3.png"
        }
    },
    {
        "type_of": "article",
        "id": 2241152,
        "title": "Is there Any Unique Project Ideas left?",
        "description": "Hi dev! We all know that to become a good dev we need to be unique in this competitive world and we...",
        "readable_publish_date": "Jan 26",
        "slug": "is-there-any-unique-project-ideas-left-1jl3",
        "path": "/lakshita_kumawat/is-there-any-unique-project-ideas-left-1jl3",
        "url": "https://dev.to/lakshita_kumawat/is-there-any-unique-project-ideas-left-1jl3",
        "comments_count": 29,
        "public_reactions_count": 36,
        "collection_id": null,
        "published_timestamp": "2025-01-26T05:39:56Z",
        "language": "en",
        "subforem_id": 1,
        "positive_reactions_count": 36,
        "cover_image": null,
        "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2F8xyz9q345nkxgv8he658.png",
        "canonical_url": "https://dev.to/lakshita_kumawat/is-there-any-unique-project-ideas-left-1jl3",
        "created_at": "2025-01-26T04:51:51Z",
        "edited_at": "2025-01-26T08:53:39Z",
        "crossposted_at": null,
        "published_at": "2025-01-26T05:39:56Z",
        "last_comment_at": "2025-01-28T15:25:53Z",
        "reading_time_minutes": 1,
        "tag_list": [
            "developers",
            "programming",
            "help",
            "discuss"
        ],
        "tags": "developers, programming, help, discuss",
        "user": {
            "name": "Lakshita Kumawat",
            "username": "lakshita_kumawat",
            "twitter_username": null,
            "github_username": null,
            "user_id": 1741476,
            "website_url": null,
            "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F1741476%2F47504ad4-a42d-40e7-9837-3ea92eba7000.png",
            "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F1741476%2F47504ad4-a42d-40e7-9837-3ea92eba7000.png"
        },
        "flare_tag": {
            "name": "help",
            "bg_color_hex": "#ff3232",
            "text_color_hex": "#ffffff"
        }
    },
    {
        "type_of": "article",
        "id": 2236718,
        "title": "Congrats to the GitHub Copilot 1-Day Build Challenge Winners!",
        "description": "Today’s the day! We are excited to announce the winners of the GitHub Copilot Challenge.  With over...",
        "readable_publish_date": "Jan 23",
        "slug": "congrats-to-the-github-copilot-1-day-build-challenge-winners-4iok",
        "path": "/devteam/congrats-to-the-github-copilot-1-day-build-challenge-winners-4iok",
        "url": "https://dev.to/devteam/congrats-to-the-github-copilot-1-day-build-challenge-winners-4iok",
        "comments_count": 22,
        "public_reactions_count": 125,
        "collection_id": null,
        "published_timestamp": "2025-01-23T19:15:03Z",
        "language": "en",
        "subforem_id": 1,
        "positive_reactions_count": 125,
        "cover_image": "https://media2.dev.to/dynamic/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fthuebn2brj8llkg6vhvv.png",
        "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fthuebn2brj8llkg6vhvv.png",
        "canonical_url": "https://dev.to/devteam/congrats-to-the-github-copilot-1-day-build-challenge-winners-4iok",
        "created_at": "2025-01-23T18:32:17Z",
        "edited_at": null,
        "crossposted_at": null,
        "published_at": "2025-01-23T19:15:03Z",
        "last_comment_at": "2025-01-27T13:08:45Z",
        "reading_time_minutes": 2,
        "tag_list": [
            "devchallenge",
            "githubchallenge",
            "ai",
            "webdev"
        ],
        "tags": "devchallenge, githubchallenge, ai, webdev",
        "user": {
            "name": "dev.to staff",
            "username": "thepracticaldev",
            "twitter_username": "ThePracticalDev",
            "github_username": null,
            "user_id": 3,
            "website_url": "https://dev.to",
            "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F3%2F13d3b32a-d381-4549-b95e-ec665768ce8f.png",
            "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F3%2F13d3b32a-d381-4549-b95e-ec665768ce8f.png"
        },
        "organization": {
            "name": "The DEV Team",
            "username": "devteam",
            "slug": "devteam",
            "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F1%2Fd908a186-5651-4a5a-9f76-15200bc6801f.jpg",
            "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F1%2Fd908a186-5651-4a5a-9f76-15200bc6801f.jpg"
        }
    },
    {
        "type_of": "article",
        "id": 2243140,
        "title": "Initial load performance for React developers: investigative deep dive",
        "description": "Table of contents                  Introducing initial load performance metrics          ...",
        "readable_publish_date": "Jan 27",
        "slug": "initial-load-performance-for-react-developers-investigative-deep-dive-ani",
        "path": "/adevnadia/initial-load-performance-for-react-developers-investigative-deep-dive-ani",
        "url": "https://dev.to/adevnadia/initial-load-performance-for-react-developers-investigative-deep-dive-ani",
        "comments_count": 2,
        "public_reactions_count": 8,
        "collection_id": null,
        "published_timestamp": "2025-01-27T09:04:00Z",
        "language": "en",
        "subforem_id": 1,
        "positive_reactions_count": 8,
        "cover_image": null,
        "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fwetwjkispst8livoqdtu.png",
        "canonical_url": "https://www.developerway.com/posts/initial-load-performance",
        "created_at": "2025-01-27T02:56:24Z",
        "edited_at": null,
        "crossposted_at": null,
        "published_at": "2025-01-27T09:04:00Z",
        "last_comment_at": "2025-01-28T11:19:32Z",
        "reading_time_minutes": 26,
        "tag_list": [
            "webdev",
            "javascript",
            "webperf",
            "performance"
        ],
        "tags": "webdev, javascript, webperf, performance",
        "user": {
            "name": "Nadia Makarevich",
            "username": "adevnadia",
            "twitter_username": "adevnadia",
            "github_username": "adevnadia",
            "user_id": 762035,
            "website_url": "https://www.developerway.com",
            "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F762035%2F1f7fe6e4-1e60-4c01-80cc-532142263682.jpg",
            "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F762035%2F1f7fe6e4-1e60-4c01-80cc-532142263682.jpg"
        }
    },
    {
        "type_of": "article",
        "id": 2196357,
        "title": "What was your win this week!?",
        "description": "👋👋👋👋  Looking back on your week -- what was something you're proud of?  All wins count -- big or...",
        "readable_publish_date": "Jan 24",
        "slug": "what-was-your-win-this-week-odp",
        "path": "/devteam/what-was-your-win-this-week-odp",
        "url": "https://dev.to/devteam/what-was-your-win-this-week-odp",
        "comments_count": 9,
        "public_reactions_count": 22,
        "collection_id": null,
        "published_timestamp": "2025-01-24T05:00:00Z",
        "language": "en",
        "subforem_id": 1,
        "positive_reactions_count": 22,
        "cover_image": "https://media2.dev.to/dynamic/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fkz1oxyn35o3d38pabxjd.jpg",
        "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fkz1oxyn35o3d38pabxjd.jpg",
        "canonical_url": "https://dev.to/devteam/what-was-your-win-this-week-odp",
        "created_at": "2025-01-08T19:44:26Z",
        "edited_at": "2025-01-08T20:06:45Z",
        "crossposted_at": null,
        "published_at": "2025-01-24T05:00:00Z",
        "last_comment_at": "2025-01-26T09:15:03Z",
        "reading_time_minutes": 1,
        "tag_list": [
            "weeklyretro",
            "discuss"
        ],
        "tags": "weeklyretro, discuss",
        "user": {
            "name": "Jess Lee",
            "username": "jess",
            "twitter_username": "jessleenyc",
            "github_username": "jessleenyc",
            "user_id": 264,
            "website_url": null,
            "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F264%2F40d89fb9-4de0-414d-8a06-f52ddda0bc75.jpg",
            "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F264%2F40d89fb9-4de0-414d-8a06-f52ddda0bc75.jpg"
        },
        "organization": {
            "name": "The DEV Team",
            "username": "devteam",
            "slug": "devteam",
            "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F1%2Fd908a186-5651-4a5a-9f76-15200bc6801f.jpg",
            "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F1%2Fd908a186-5651-4a5a-9f76-15200bc6801f.jpg"
        },
        "flare_tag": {
            "name": "discuss",
            "bg_color_hex": "#71EA8B",
            "text_color_hex": "#FFFFFF"
        }
    },
    {
        "type_of": "article",
        "id": 2242377,
        "title": "Streaming an AI Project starting 2025",
        "description": "It’s been a while and for good reasons, I’ve been cooking up something special.  Back in July last...",
        "readable_publish_date": "Jan 27",
        "slug": "streaming-an-ai-project-starting-2025-nej",
        "path": "/sebastianccc/streaming-an-ai-project-starting-2025-nej",
        "url": "https://dev.to/sebastianccc/streaming-an-ai-project-starting-2025-nej",
        "comments_count": 7,
        "public_reactions_count": 22,
        "collection_id": null,
        "published_timestamp": "2025-01-27T11:30:46Z",
        "language": "en",
        "subforem_id": 1,
        "positive_reactions_count": 22,
        "cover_image": "https://media2.dev.to/dynamic/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2F5etfoqa22j9z514o8d3p.png",
        "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2F5etfoqa22j9z514o8d3p.png",
        "canonical_url": "https://dev.to/sebastianccc/streaming-an-ai-project-starting-2025-nej",
        "created_at": "2025-01-26T17:21:05Z",
        "edited_at": null,
        "crossposted_at": null,
        "published_at": "2025-01-27T11:30:46Z",
        "last_comment_at": "2025-01-28T15:44:24Z",
        "reading_time_minutes": 1,
        "tag_list": [
            "ai",
            "news",
            "opensource",
            "api"
        ],
        "tags": "ai, news, opensource, api",
        "user": {
            "name": "Sebastian Christopher",
            "username": "sebastianccc",
            "twitter_username": null,
            "github_username": "SebastianCCC",
            "user_id": 813511,
            "website_url": null,
            "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F813511%2F4c4f8a95-b7be-4897-b801-8ee065467d8d.jpeg",
            "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F813511%2F4c4f8a95-b7be-4897-b801-8ee065467d8d.jpeg"
        },
        "flare_tag": {
            "name": "news",
            "bg_color_hex": "#111111",
            "text_color_hex": "#fff9ac"
        }
    },
    {
        "type_of": "article",
        "id": 2240010,
        "title": "Building Hounty: Baby steps",
        "description": "I've been building software for sixteen years. I've built countless websites, mobile apps, backend...",
        "readable_publish_date": "Jan 25",
        "slug": "building-an-app-baby-steps-2jb7",
        "path": "/valeriavg/building-an-app-baby-steps-2jb7",
        "url": "https://dev.to/valeriavg/building-an-app-baby-steps-2jb7",
        "comments_count": 14,
        "public_reactions_count": 61,
        "collection_id": null,
        "published_timestamp": "2025-01-25T10:56:24Z",
        "language": "en",
        "subforem_id": 1,
        "positive_reactions_count": 61,
        "cover_image": "https://media2.dev.to/dynamic/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2F6n36u9hn59v0zdbj6esv.png",
        "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2F6n36u9hn59v0zdbj6esv.png",
        "canonical_url": "https://dev.to/valeriavg/building-an-app-baby-steps-2jb7",
        "created_at": "2025-01-25T10:56:25Z",
        "edited_at": "2025-01-25T11:07:20Z",
        "crossposted_at": null,
        "published_at": "2025-01-25T10:56:24Z",
        "last_comment_at": "2025-01-27T21:15:11Z",
        "reading_time_minutes": 6,
        "tag_list": [
            "startup",
            "devjournal",
            "webdev"
        ],
        "tags": "startup, devjournal, webdev",
        "user": {
            "name": "Valeria",
            "username": "valeriavg",
            "twitter_username": "DeValeriaVG",
            "github_username": "ValeriaVG",
            "user_id": 473770,
            "website_url": "https://valeriavg.dev",
            "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F473770%2F2ee31638-e52d-40f9-8bf8-d98b82784a4b.jpg",
            "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F473770%2F2ee31638-e52d-40f9-8bf8-d98b82784a4b.jpg"
        }
    },
    {
        "type_of": "article",
        "id": 2190298,
        "title": "Yay! I created my first Portfolio! 🎉",
        "description": "After months of hard work, I'm finally launching my portfolio to show the world.  I've always...",
        "readable_publish_date": "Jan 24",
        "slug": "yay-i-created-my-first-portfolio-375",
        "path": "/anmolbaranwal/yay-i-created-my-first-portfolio-375",
        "url": "https://dev.to/anmolbaranwal/yay-i-created-my-first-portfolio-375",
        "comments_count": 43,
        "public_reactions_count": 172,
        "collection_id": null,
        "published_timestamp": "2025-01-24T08:18:30Z",
        "language": "en",
        "subforem_id": 1,
        "positive_reactions_count": 172,
        "cover_image": "https://media2.dev.to/dynamic/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fatc1m2bghffnm4dr5uza.png",
        "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fatc1m2bghffnm4dr5uza.png",
        "canonical_url": "https://dev.to/anmolbaranwal/yay-i-created-my-first-portfolio-375",
        "created_at": "2025-01-05T19:05:45Z",
        "edited_at": null,
        "crossposted_at": null,
        "published_at": "2025-01-24T08:18:30Z",
        "last_comment_at": "2025-01-28T13:50:08Z",
        "reading_time_minutes": 4,
        "tag_list": [
            "portfolio",
            "nextjs",
            "showdev",
            "programming"
        ],
        "tags": "portfolio, nextjs, showdev, programming",
        "user": {
            "name": "Anmol Baranwal",
            "username": "anmolbaranwal",
            "twitter_username": "Anmol_Codes",
            "github_username": "Anmol-Baranwal",
            "user_id": 950976,
            "website_url": "https://anmolbaranwal.com",
            "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F950976%2F69363f37-b7c5-4f1e-a2fe-29b4e4e33e92.png",
            "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F950976%2F69363f37-b7c5-4f1e-a2fe-29b4e4e33e92.png"
        },
        "flare_tag": {
            "name": "showdev",
            "bg_color_hex": "#091b47",
            "text_color_hex": "#b2ffe1"
        }
    },
    {
        "type_of": "article",
        "id": 2236756,
        "title": "Building a RESTful API with ASP.NET Core, Swagger, and Neon",
        "description": "In this guide, we'll walk through the process of developing a RESTful API using ASP.NET Core,...",
        "readable_publish_date": "Jan 23",
        "slug": "building-a-restful-api-with-aspnet-core-swagger-and-neon-9el",
        "path": "/neon-postgres/building-a-restful-api-with-aspnet-core-swagger-and-neon-9el",
        "url": "https://dev.to/neon-postgres/building-a-restful-api-with-aspnet-core-swagger-and-neon-9el",
        "comments_count": 0,
        "public_reactions_count": 6,
        "collection_id": null,
        "published_timestamp": "2025-01-23T19:19:14Z",
        "language": "en",
        "subforem_id": 1,
        "positive_reactions_count": 6,
        "cover_image": null,
        "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2F7iog1b7864vtre8t4kos.png",
        "canonical_url": "https://dev.to/neon-postgres/building-a-restful-api-with-aspnet-core-swagger-and-neon-9el",
        "created_at": "2025-01-23T19:14:14Z",
        "edited_at": null,
        "crossposted_at": null,
        "published_at": "2025-01-23T19:19:14Z",
        "last_comment_at": "2025-01-23T19:19:14Z",
        "reading_time_minutes": 10,
        "tag_list": [
            "webdev",
            "postgressql",
            "programming",
            "tutorial"
        ],
        "tags": "webdev, postgressql, programming, tutorial",
        "user": {
            "name": "Rishi Raj Jain",
            "username": "reeshee",
            "twitter_username": null,
            "github_username": "rishi-raj-jain",
            "user_id": 241008,
            "website_url": "https://www.launchfa.st",
            "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F241008%2F1ccd6ac7-448e-4408-90d3-047a206d4b2d.png",
            "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F241008%2F1ccd6ac7-448e-4408-90d3-047a206d4b2d.png"
        },
        "organization": {
            "name": "Neon",
            "username": "neon-postgres",
            "slug": "neon-postgres",
            "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F8214%2F1dedca6f-d508-49c2-8b23-220904e7dbe7.jpeg",
            "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F8214%2F1dedca6f-d508-49c2-8b23-220904e7dbe7.jpeg"
        }
    },
    {
        "type_of": "article",
        "id": 2240100,
        "title": "The <sarcasm> 🙄 component - now Brits can finally be understood on the web!",
        "description": "I don't think 'Muricans understand our struggle as Brits.  We make a killer sarcastic comment like \"I...",
        "readable_publish_date": "Jan 25",
        "slug": "the-component-now-brits-can-finally-be-understood-on-the-web-33m1",
        "path": "/grahamthedev/the-component-now-brits-can-finally-be-understood-on-the-web-33m1",
        "url": "https://dev.to/grahamthedev/the-component-now-brits-can-finally-be-understood-on-the-web-33m1",
        "comments_count": 29,
        "public_reactions_count": 59,
        "collection_id": null,
        "published_timestamp": "2025-01-25T11:43:45Z",
        "language": "en",
        "subforem_id": 1,
        "positive_reactions_count": 59,
        "cover_image": "https://media2.dev.to/dynamic/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Faxfjmmdbdkcxif4k5frx.jpg",
        "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Faxfjmmdbdkcxif4k5frx.jpg",
        "canonical_url": "https://dev.to/grahamthedev/the-component-now-brits-can-finally-be-understood-on-the-web-33m1",
        "created_at": "2025-01-25T11:43:46Z",
        "edited_at": "2025-01-25T12:38:39Z",
        "crossposted_at": null,
        "published_at": "2025-01-25T11:43:45Z",
        "last_comment_at": "2025-01-28T10:11:26Z",
        "reading_time_minutes": 2,
        "tag_list": [
            "programming",
            "javascript",
            "css",
            "webdev"
        ],
        "tags": "programming, javascript, css, webdev",
        "user": {
            "name": "GrahamTheDev",
            "username": "grahamthedev",
            "twitter_username": "GrahamTheDev",
            "github_username": null,
            "user_id": 551686,
            "website_url": null,
            "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F551686%2Ff0514090-260b-4a34-89b0-a2b6e922d5ec.jpg",
            "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F551686%2Ff0514090-260b-4a34-89b0-a2b6e922d5ec.jpg"
        }
    },
    {
        "type_of": "article",
        "id": 2238415,
        "title": "X Profile Roaster 🌶️🔥❤️‍🔥",
        "description": "This is a submission for the Agent.ai Challenge: Assembly of Agents (See Details)           What I...",
        "readable_publish_date": "Jan 24",
        "slug": "x-profile-roaster-1ca0",
        "path": "/divya4879/x-profile-roaster-1ca0",
        "url": "https://dev.to/divya4879/x-profile-roaster-1ca0",
        "comments_count": 12,
        "public_reactions_count": 42,
        "collection_id": null,
        "published_timestamp": "2025-01-24T13:52:18Z",
        "language": "en",
        "subforem_id": 1,
        "positive_reactions_count": 42,
        "cover_image": "https://media2.dev.to/dynamic/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Far8o0bg2du2tpwtlsmkl.jpg",
        "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Far8o0bg2du2tpwtlsmkl.jpg",
        "canonical_url": "https://dev.to/divya4879/x-profile-roaster-1ca0",
        "created_at": "2025-01-24T11:53:47Z",
        "edited_at": null,
        "crossposted_at": null,
        "published_at": "2025-01-24T13:52:18Z",
        "last_comment_at": "2025-01-28T11:48:11Z",
        "reading_time_minutes": 3,
        "tag_list": [
            "devchallenge",
            "agentaichallenge",
            "ai",
            "machinelearning"
        ],
        "tags": "devchallenge, agentaichallenge, ai, machinelearning",
        "user": {
            "name": "Div_dev",
            "username": "divya4879",
            "twitter_username": null,
            "github_username": "Divya4879",
            "user_id": 889475,
            "website_url": null,
            "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F889475%2Ffca1ced1-3df6-465a-82c4-f14d29f6c26e.jpeg",
            "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F889475%2Ffca1ced1-3df6-465a-82c4-f14d29f6c26e.jpeg"
        }
    },
    {
        "type_of": "article",
        "id": 2237071,
        "title": "Showcase your open source project at SCALE 🐧 Pasadena, CA · March 6-9, 2025",
        "description": "Hi everyone! 👋  We're thrilled to invite open source maintainers to an amazing opportunity:...",
        "readable_publish_date": "Jan 24",
        "slug": "showcase-your-open-source-project-at-scale-pasadena-ca-march-6-9-2025-12kn",
        "path": "/github/showcase-your-open-source-project-at-scale-pasadena-ca-march-6-9-2025-12kn",
        "url": "https://dev.to/github/showcase-your-open-source-project-at-scale-pasadena-ca-march-6-9-2025-12kn",
        "comments_count": 2,
        "public_reactions_count": 25,
        "collection_id": null,
        "published_timestamp": "2025-01-24T17:51:20Z",
        "language": "en",
        "subforem_id": 1,
        "positive_reactions_count": 25,
        "cover_image": "https://media2.dev.to/dynamic/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fvzbpeehc1nzwhcmmwal7.png",
        "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fvzbpeehc1nzwhcmmwal7.png",
        "canonical_url": "https://dev.to/github/showcase-your-open-source-project-at-scale-pasadena-ca-march-6-9-2025-12kn",
        "created_at": "2025-01-24T01:02:50Z",
        "edited_at": null,
        "crossposted_at": null,
        "published_at": "2025-01-24T17:51:20Z",
        "last_comment_at": "2025-01-28T11:14:09Z",
        "reading_time_minutes": 2,
        "tag_list": [
            "github",
            "linux",
            "opensource"
        ],
        "tags": "github, linux, opensource",
        "user": {
            "name": "Lee Reilly",
            "username": "leereilly",
            "twitter_username": "leereilly",
            "github_username": "leereilly",
            "user_id": 41834,
            "website_url": "https://leereilly.net",
            "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F41834%2F5e784354-ab2c-4109-9d84-6e64c24879bc.jpeg",
            "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F41834%2F5e784354-ab2c-4109-9d84-6e64c24879bc.jpeg"
        },
        "organization": {
            "name": "GitHub",
            "username": "github",
            "slug": "github",
            "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F2575%2F3da37f64-b46e-4fa5-bf86-01b63ba5f57b.png",
            "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F2575%2F3da37f64-b46e-4fa5-bf86-01b63ba5f57b.png"
        }
    },
    {
        "type_of": "article",
        "id": 2231575,
        "title": "Top 7 Featured DEV Posts of the Week",
        "description": "Welcome to this week's Top 7, where the DEV editorial team handpicks their favorite posts from the...",
        "readable_publish_date": "Jan 21",
        "slug": "top-7-featured-dev-posts-of-the-week-3ob4",
        "path": "/devteam/top-7-featured-dev-posts-of-the-week-3ob4",
        "url": "https://dev.to/devteam/top-7-featured-dev-posts-of-the-week-3ob4",
        "comments_count": 2,
        "public_reactions_count": 34,
        "collection_id": null,
        "published_timestamp": "2025-01-21T18:12:04Z",
        "language": "en",
        "subforem_id": 1,
        "positive_reactions_count": 34,
        "cover_image": "https://media2.dev.to/dynamic/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fi72nxav9bmvmx84dpo6m.jpg",
        "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fi72nxav9bmvmx84dpo6m.jpg",
        "canonical_url": "https://dev.to/devteam/top-7-featured-dev-posts-of-the-week-3ob4",
        "created_at": "2025-01-21T18:03:45Z",
        "edited_at": null,
        "crossposted_at": null,
        "published_at": "2025-01-21T18:12:04Z",
        "last_comment_at": "2025-01-22T04:11:08Z",
        "reading_time_minutes": 2,
        "tag_list": [
            "top7"
        ],
        "tags": "top7",
        "user": {
            "name": "dev.to staff",
            "username": "thepracticaldev",
            "twitter_username": "ThePracticalDev",
            "github_username": null,
            "user_id": 3,
            "website_url": "https://dev.to",
            "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F3%2F13d3b32a-d381-4549-b95e-ec665768ce8f.png",
            "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F3%2F13d3b32a-d381-4549-b95e-ec665768ce8f.png"
        },
        "organization": {
            "name": "The DEV Team",
            "username": "devteam",
            "slug": "devteam",
            "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F1%2Fd908a186-5651-4a5a-9f76-15200bc6801f.jpg",
            "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F1%2Fd908a186-5651-4a5a-9f76-15200bc6801f.jpg"
        }
    },
    {
        "type_of": "article",
        "id": 2234052,
        "title": "Oldie but goodie",
        "description": "What's playing in your headphones while you code?       Ben...",
        "readable_publish_date": "Jan 22",
        "slug": "oldie-but-goodie-1kdc",
        "path": "/ben/oldie-but-goodie-1kdc",
        "url": "https://dev.to/ben/oldie-but-goodie-1kdc",
        "comments_count": 4,
        "public_reactions_count": 6,
        "collection_id": null,
        "published_timestamp": "2025-01-22T18:33:08Z",
        "language": "en",
        "subforem_id": 1,
        "positive_reactions_count": 6,
        "cover_image": null,
        "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fiqi6lg5exuuxdlvrx3gm.png",
        "canonical_url": "https://dev.to/ben/oldie-but-goodie-1kdc",
        "created_at": "2025-01-22T18:33:08Z",
        "edited_at": null,
        "crossposted_at": null,
        "published_at": "2025-01-22T18:33:08Z",
        "last_comment_at": "2025-01-25T03:21:50Z",
        "reading_time_minutes": 1,
        "tag_list": [
            "discuss",
            "watercooler"
        ],
        "tags": "discuss, watercooler",
        "user": {
            "name": "Ben Halpern",
            "username": "ben",
            "twitter_username": "bendhalpern",
            "github_username": "benhalpern",
            "user_id": 1,
            "website_url": "http://benhalpern.com",
            "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F1%2Ff451a206-11c8-4e3d-8936-143d0a7e65bb.png",
            "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F1%2Ff451a206-11c8-4e3d-8936-143d0a7e65bb.png"
        },
        "flare_tag": {
            "name": "discuss",
            "bg_color_hex": "#71EA8B",
            "text_color_hex": "#FFFFFF"
        }
    },
    {
        "type_of": "article",
        "id": 2232938,
        "title": "Go Beyond the Basics: Connecting Compute to Object Storage with the Official S3 Clients",
        "description": "Fastly Compute has consistently supported developers through its SDK with strong APIs for persistence...",
        "readable_publish_date": "Jan 24",
        "slug": "go-beyond-the-basics-connecting-compute-to-object-storage-with-the-official-s3-clients-4l9p",
        "path": "/fastly/go-beyond-the-basics-connecting-compute-to-object-storage-with-the-official-s3-clients-4l9p",
        "url": "https://dev.to/fastly/go-beyond-the-basics-connecting-compute-to-object-storage-with-the-official-s3-clients-4l9p",
        "comments_count": 0,
        "public_reactions_count": 3,
        "collection_id": null,
        "published_timestamp": "2025-01-24T21:42:24Z",
        "language": "en",
        "subforem_id": 1,
        "positive_reactions_count": 3,
        "cover_image": null,
        "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Flv9mpzw2eglpehghxhsg.png",
        "canonical_url": "https://dev.to/fastly/go-beyond-the-basics-connecting-compute-to-object-storage-with-the-official-s3-clients-4l9p",
        "created_at": "2025-01-22T09:51:14Z",
        "edited_at": null,
        "crossposted_at": null,
        "published_at": "2025-01-24T21:42:24Z",
        "last_comment_at": "2025-01-24T21:42:24Z",
        "reading_time_minutes": 5,
        "tag_list": [
            "fastly",
            "serverless",
            "webassembly",
            "s3"
        ],
        "tags": "fastly, serverless, webassembly, s3",
        "user": {
            "name": "Kay Sawada",
            "username": "kaysawada",
            "twitter_username": null,
            "github_username": null,
            "user_id": 2746632,
            "website_url": null,
            "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F2746632%2F4147e324-0337-4908-bdda-16b4fc088421.jpg",
            "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F2746632%2F4147e324-0337-4908-bdda-16b4fc088421.jpg"
        },
        "organization": {
            "name": "Fastly",
            "username": "fastly",
            "slug": "fastly",
            "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F2298%2F27608760-4be1-4e12-b054-b8a2748d978d.png",
            "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F2298%2F27608760-4be1-4e12-b054-b8a2748d978d.png"
        }
    },
    {
        "type_of": "article",
        "id": 2207857,
        "title": "Top 7 Featured DEV Posts of the Week",
        "description": "Welcome to this week's Top 7, where the DEV editorial team handpicks their favorite posts from the...",
        "readable_publish_date": "Jan 14",
        "slug": "top-7-featured-dev-posts-of-the-week-528",
        "path": "/devteam/top-7-featured-dev-posts-of-the-week-528",
        "url": "https://dev.to/devteam/top-7-featured-dev-posts-of-the-week-528",
        "comments_count": 4,
        "public_reactions_count": 27,
        "collection_id": null,
        "published_timestamp": "2025-01-14T15:57:47Z",
        "language": "en",
        "subforem_id": 1,
        "positive_reactions_count": 27,
        "cover_image": "https://media2.dev.to/dynamic/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fc2hhi7u516kboi6nhrsu.jpg",
        "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fc2hhi7u516kboi6nhrsu.jpg",
        "canonical_url": "https://dev.to/devteam/top-7-featured-dev-posts-of-the-week-528",
        "created_at": "2025-01-14T15:57:06Z",
        "edited_at": null,
        "crossposted_at": null,
        "published_at": "2025-01-14T15:57:47Z",
        "last_comment_at": "2025-01-16T20:15:08Z",
        "reading_time_minutes": 2,
        "tag_list": [
            "top7"
        ],
        "tags": "top7",
        "user": {
            "name": "dev.to staff",
            "username": "thepracticaldev",
            "twitter_username": "ThePracticalDev",
            "github_username": null,
            "user_id": 3,
            "website_url": "https://dev.to",
            "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F3%2F13d3b32a-d381-4549-b95e-ec665768ce8f.png",
            "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F3%2F13d3b32a-d381-4549-b95e-ec665768ce8f.png"
        },
        "organization": {
            "name": "The DEV Team",
            "username": "devteam",
            "slug": "devteam",
            "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F1%2Fd908a186-5651-4a5a-9f76-15200bc6801f.jpg",
            "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F1%2Fd908a186-5651-4a5a-9f76-15200bc6801f.jpg"
        }
    },
    {
        "type_of": "article",
        "id": 2193439,
        "title": "Why I Decided to Stop Working with React.js in 2025",
        "description": "After years of working with React, I’ve decided to move on. Here’s why React isn’t my framework of choice anymore.",
        "readable_publish_date": "Jan 7",
        "slug": "why-i-decided-to-stop-working-with-reactjs-in-2025-4d1l",
        "path": "/holasoymalva/why-i-decided-to-stop-working-with-reactjs-in-2025-4d1l",
        "url": "https://dev.to/holasoymalva/why-i-decided-to-stop-working-with-reactjs-in-2025-4d1l",
        "comments_count": 129,
        "public_reactions_count": 257,
        "collection_id": null,
        "published_timestamp": "2025-01-07T17:47:25Z",
        "language": "en",
        "subforem_id": 1,
        "positive_reactions_count": 257,
        "cover_image": "https://media2.dev.to/dynamic/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fimages.unsplash.com%2Fphoto-1570798304553-48a703bfb2aa%3Fq%3D80%26w%3D2070%26auto%3Dformat%26fit%3Dcrop%26ixlib%3Drb-4.0.3%26ixid%3DM3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%253D%253D",
        "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fimages.unsplash.com%2Fphoto-1570798304553-48a703bfb2aa%3Fq%3D80%26w%3D2070%26auto%3Dformat%26fit%3Dcrop%26ixlib%3Drb-4.0.3%26ixid%3DM3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%253D%253D",
        "canonical_url": "https://dev.to/holasoymalva/why-i-decided-to-stop-working-with-reactjs-in-2025-4d1l",
        "created_at": "2025-01-07T17:47:25Z",
        "edited_at": null,
        "crossposted_at": null,
        "published_at": "2025-01-07T17:47:25Z",
        "last_comment_at": "2025-01-20T03:00:57Z",
        "reading_time_minutes": 4,
        "tag_list": [
            "javascript",
            "react",
            "node",
            "programming"
        ],
        "tags": "javascript, react, node, programming",
        "user": {
            "name": "Leon Martin",
            "username": "holasoymalva",
            "twitter_username": "holasoymalva",
            "github_username": "holasoymalva",
            "user_id": 127521,
            "website_url": "https://holasoymalva.com",
            "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F127521%2F042a1c32-81ce-4920-9ac1-2b120d12225c.png",
            "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F127521%2F042a1c32-81ce-4920-9ac1-2b120d12225c.png"
        }
    },
    {
        "type_of": "article",
        "id": 2231842,
        "title": "Run DeepSeek-R1 on Your Laptop with Ollama",
        "description": "Yesterday, DeepSeek released a series of very powerful language models including DeepSeek R1 and a...",
        "readable_publish_date": "Jan 21",
        "slug": "run-deepseek-locally-on-your-laptop-37hl",
        "path": "/shayy/run-deepseek-locally-on-your-laptop-37hl",
        "url": "https://dev.to/shayy/run-deepseek-locally-on-your-laptop-37hl",
        "comments_count": 16,
        "public_reactions_count": 411,
        "collection_id": null,
        "published_timestamp": "2025-01-21T21:30:45Z",
        "language": "en",
        "subforem_id": 1,
        "positive_reactions_count": 411,
        "cover_image": "https://media2.dev.to/dynamic/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2F0riixk5v2iptp8tqpqif.png",
        "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2F0riixk5v2iptp8tqpqif.png",
        "canonical_url": "https://dev.to/shayy/run-deepseek-locally-on-your-laptop-37hl",
        "created_at": "2025-01-21T21:30:50Z",
        "edited_at": "2025-01-28T04:26:20Z",
        "crossposted_at": null,
        "published_at": "2025-01-21T21:30:45Z",
        "last_comment_at": "2025-01-28T04:07:31Z",
        "reading_time_minutes": 10,
        "tag_list": [
            "ai",
            "llm",
            "tutorial",
            "productivity"
        ],
        "tags": "ai, llm, tutorial, productivity",
        "user": {
            "name": "Shayan",
            "username": "shayy",
            "twitter_username": null,
            "github_username": null,
            "user_id": 2711665,
            "website_url": null,
            "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F2711665%2Fe528db00-6ac0-4654-b0d5-c68d84ed332e.png",
            "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F2711665%2Fe528db00-6ac0-4654-b0d5-c68d84ed332e.png"
        }
    },
    {
        "type_of": "article",
        "id": 2222353,
        "title": "Bridge: Empowering Communities and Fresh Starts with GitHub Copilot",
        "description": "Hi there! This is my entry for the GitHub Copilot Challenge: Fresh Starts           What I...",
        "readable_publish_date": "Jan 18",
        "slug": "bridge-empowering-communities-and-fresh-starts-with-github-copilot-5efl",
        "path": "/sgfhonestant/bridge-empowering-communities-and-fresh-starts-with-github-copilot-5efl",
        "url": "https://dev.to/sgfhonestant/bridge-empowering-communities-and-fresh-starts-with-github-copilot-5efl",
        "comments_count": 0,
        "public_reactions_count": 8,
        "collection_id": null,
        "published_timestamp": "2025-01-18T12:15:08Z",
        "language": "en",
        "subforem_id": 1,
        "positive_reactions_count": 8,
        "cover_image": null,
        "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fi5zufluf075e1wxd6hy9.png",
        "canonical_url": "https://dev.to/sgfhonestant/bridge-empowering-communities-and-fresh-starts-with-github-copilot-5efl",
        "created_at": "2025-01-18T12:15:09Z",
        "edited_at": null,
        "crossposted_at": null,
        "published_at": "2025-01-18T12:15:08Z",
        "last_comment_at": "2025-01-18T12:15:08Z",
        "reading_time_minutes": 2,
        "tag_list": [
            "devchallenge",
            "githubchallenge",
            "webdev",
            "ai"
        ],
        "tags": "devchallenge, githubchallenge, webdev, ai",
        "user": {
            "name": "Sarah Fisher",
            "username": "sgfhonestant",
            "twitter_username": null,
            "github_username": "sgf-HonestAnt",
            "user_id": 1432981,
            "website_url": null,
            "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F1432981%2F76a4e3fd-8bc6-458b-b044-bd6fe96ab87a.jpeg",
            "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F1432981%2F76a4e3fd-8bc6-458b-b044-bd6fe96ab87a.jpeg"
        }
    },
    {
        "type_of": "article",
        "id": 2223094,
        "title": "Making binary search slower",
        "description": "Experience the power of binary search with a creative twist! By adding a 1-second delay per iteration, this post visualizes how the algorithm efficiently narrows down massive datasets, making its logarithmic scaling tangible. Perfect for learners and educators!",
        "readable_publish_date": "Jan 18",
        "slug": "making-binary-search-slower-5h97",
        "path": "/acoh3n/making-binary-search-slower-5h97",
        "url": "https://dev.to/acoh3n/making-binary-search-slower-5h97",
        "comments_count": 1,
        "public_reactions_count": 10,
        "collection_id": null,
        "published_timestamp": "2025-01-18T20:52:55Z",
        "language": "en",
        "subforem_id": 1,
        "positive_reactions_count": 10,
        "cover_image": "https://media2.dev.to/dynamic/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fri9jvjbdzpvr923lrnor.jpg",
        "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fri9jvjbdzpvr923lrnor.jpg",
        "canonical_url": "https://dev.to/acoh3n/making-binary-search-slower-5h97",
        "created_at": "2025-01-18T20:18:25Z",
        "edited_at": "2025-01-18T20:54:45Z",
        "crossposted_at": null,
        "published_at": "2025-01-18T20:52:55Z",
        "last_comment_at": "2025-01-21T11:57:36Z",
        "reading_time_minutes": 4,
        "tag_list": [
            "algorithms",
            "computerscience",
            "binarysearch"
        ],
        "tags": "algorithms, computerscience, binarysearch",
        "user": {
            "name": "Arik",
            "username": "acoh3n",
            "twitter_username": null,
            "github_username": "okayrunner",
            "user_id": 74828,
            "website_url": "https://arikcohen.com",
            "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F74828%2F4a9403cb-2190-42db-944f-58cf655c1495.jpg",
            "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F74828%2F4a9403cb-2190-42db-944f-58cf655c1495.jpg"
        }
    },
    {
        "type_of": "article",
        "id": 2220605,
        "title": "vueframe V3 is here !!!",
        "description": "Hey guys I officially have released V3 of vueframe, adding a bunch of quality of life improvements...",
        "readable_publish_date": "Jan 17",
        "slug": "vueframe-v3-is-here--1cad",
        "path": "/greenestgoat/vueframe-v3-is-here--1cad",
        "url": "https://dev.to/greenestgoat/vueframe-v3-is-here--1cad",
        "comments_count": 2,
        "public_reactions_count": 11,
        "collection_id": null,
        "published_timestamp": "2025-01-17T22:15:35Z",
        "language": "en",
        "subforem_id": 1,
        "positive_reactions_count": 11,
        "cover_image": "https://media2.dev.to/dynamic/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fgg1yo77a3uy2d9bb78no.png",
        "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fgg1yo77a3uy2d9bb78no.png",
        "canonical_url": "https://dev.to/greenestgoat/vueframe-v3-is-here--1cad",
        "created_at": "2025-01-17T22:15:36Z",
        "edited_at": null,
        "crossposted_at": null,
        "published_at": "2025-01-17T22:15:35Z",
        "last_comment_at": "2025-01-20T22:33:56Z",
        "reading_time_minutes": 1,
        "tag_list": [
            "vue",
            "webdev",
            "javascript",
            "webcomponents"
        ],
        "tags": "vue, webdev, javascript, webcomponents",
        "user": {
            "name": "GreenestGoat",
            "username": "greenestgoat",
            "twitter_username": null,
            "github_username": "GreenestGoat",
            "user_id": 1599806,
            "website_url": "https://paperui.com",
            "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F1599806%2F5f18aca1-cb04-4625-b294-59510b341d23.png",
            "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F1599806%2F5f18aca1-cb04-4625-b294-59510b341d23.png"
        }
    },
    {
        "type_of": "article",
        "id": 2204220,
        "title": "Meme Monday",
        "description": "Meme Monday!  Today's cover image comes from last week's thread.  DEV is an inclusive space! Humor in...",
        "readable_publish_date": "Jan 13",
        "slug": "meme-monday-38kh",
        "path": "/ben/meme-monday-38kh",
        "url": "https://dev.to/ben/meme-monday-38kh",
        "comments_count": 43,
        "public_reactions_count": 32,
        "collection_id": null,
        "published_timestamp": "2025-01-13T14:27:14Z",
        "language": "en",
        "subforem_id": 1,
        "positive_reactions_count": 32,
        "cover_image": "https://media2.dev.to/dynamic/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2F8t6z6j1jral8mvyithsf.png",
        "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2F8t6z6j1jral8mvyithsf.png",
        "canonical_url": "https://dev.to/ben/meme-monday-38kh",
        "created_at": "2025-01-13T14:27:15Z",
        "edited_at": null,
        "crossposted_at": null,
        "published_at": "2025-01-13T14:27:14Z",
        "last_comment_at": "2025-01-26T13:22:31Z",
        "reading_time_minutes": 1,
        "tag_list": [
            "discuss",
            "watercooler",
            "jokes"
        ],
        "tags": "discuss, watercooler, jokes",
        "user": {
            "name": "Ben Halpern",
            "username": "ben",
            "twitter_username": "bendhalpern",
            "github_username": "benhalpern",
            "user_id": 1,
            "website_url": "http://benhalpern.com",
            "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F1%2Ff451a206-11c8-4e3d-8936-143d0a7e65bb.png",
            "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F1%2Ff451a206-11c8-4e3d-8936-143d0a7e65bb.png"
        },
        "flare_tag": {
            "name": "discuss",
            "bg_color_hex": "#71EA8B",
            "text_color_hex": "#FFFFFF"
        }
    },
    {
        "type_of": "article",
        "id": 2236774,
        "title": "Exploring OpenAI Operator",
        "description": "What Is Operator?   Have you ever wished you could push off repetitive online tasks to...",
        "readable_publish_date": "Jan 23",
        "slug": "exploring-openai-operator-your-ai-powered-browser-assistant-3dj2",
        "path": "/burcs/exploring-openai-operator-your-ai-powered-browser-assistant-3dj2",
        "url": "https://dev.to/burcs/exploring-openai-operator-your-ai-powered-browser-assistant-3dj2",
        "comments_count": 11,
        "public_reactions_count": 35,
        "collection_id": null,
        "published_timestamp": "2025-01-23T19:42:27Z",
        "language": "en",
        "subforem_id": 1,
        "positive_reactions_count": 35,
        "cover_image": "https://media2.dev.to/dynamic/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fxivrj46o714w1es5nm7b.png",
        "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fxivrj46o714w1es5nm7b.png",
        "canonical_url": "https://dev.to/burcs/exploring-openai-operator-your-ai-powered-browser-assistant-3dj2",
        "created_at": "2025-01-23T19:42:28Z",
        "edited_at": "2025-01-23T19:43:23Z",
        "crossposted_at": null,
        "published_at": "2025-01-23T19:42:27Z",
        "last_comment_at": "2025-01-28T04:45:12Z",
        "reading_time_minutes": 3,
        "tag_list": [
            "ai",
            "webdev",
            "database"
        ],
        "tags": "ai, webdev, database",
        "user": {
            "name": "brandon",
            "username": "burcs",
            "twitter_username": "burcs",
            "github_username": null,
            "user_id": 485605,
            "website_url": "https://www.outerbase.com",
            "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F485605%2F519a6e39-9969-46f2-9777-e40fe4040e98.jpeg",
            "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F485605%2F519a6e39-9969-46f2-9777-e40fe4040e98.jpeg"
        }
    },
    {
        "type_of": "article",
        "id": 2196355,
        "title": "What was your win this week?!",
        "description": "👋👋👋👋  Looking back on your week -- what was something you're proud of?  All wins count -- big or...",
        "readable_publish_date": "Jan 17",
        "slug": "what-was-your-win-this-week-2eei",
        "path": "/devteam/what-was-your-win-this-week-2eei",
        "url": "https://dev.to/devteam/what-was-your-win-this-week-2eei",
        "comments_count": 16,
        "public_reactions_count": 21,
        "collection_id": null,
        "published_timestamp": "2025-01-17T05:00:00Z",
        "language": "en",
        "subforem_id": 1,
        "positive_reactions_count": 21,
        "cover_image": "https://media2.dev.to/dynamic/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2F7kjf3dj02bjeug1zlk1b.jpg",
        "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2F7kjf3dj02bjeug1zlk1b.jpg",
        "canonical_url": "https://dev.to/devteam/what-was-your-win-this-week-2eei",
        "created_at": "2025-01-08T19:42:40Z",
        "edited_at": "2025-01-08T20:06:51Z",
        "crossposted_at": null,
        "published_at": "2025-01-17T05:00:00Z",
        "last_comment_at": "2025-01-22T20:43:40Z",
        "reading_time_minutes": 1,
        "tag_list": [
            "weeklyretro",
            "discuss"
        ],
        "tags": "weeklyretro, discuss",
        "user": {
            "name": "Jess Lee",
            "username": "jess",
            "twitter_username": "jessleenyc",
            "github_username": "jessleenyc",
            "user_id": 264,
            "website_url": null,
            "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F264%2F40d89fb9-4de0-414d-8a06-f52ddda0bc75.jpg",
            "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F264%2F40d89fb9-4de0-414d-8a06-f52ddda0bc75.jpg"
        },
        "organization": {
            "name": "The DEV Team",
            "username": "devteam",
            "slug": "devteam",
            "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F1%2Fd908a186-5651-4a5a-9f76-15200bc6801f.jpg",
            "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F1%2Fd908a186-5651-4a5a-9f76-15200bc6801f.jpg"
        },
        "flare_tag": {
            "name": "discuss",
            "bg_color_hex": "#71EA8B",
            "text_color_hex": "#FFFFFF"
        }
    },
    {
        "type_of": "article",
        "id": 2196354,
        "title": "What was your win this week?",
        "description": "👋👋👋👋  Looking back on your week -- what was something you're proud of?  All wins count -- big or...",
        "readable_publish_date": "Jan 10",
        "slug": "what-was-your-win-this-week-5j6",
        "path": "/devteam/what-was-your-win-this-week-5j6",
        "url": "https://dev.to/devteam/what-was-your-win-this-week-5j6",
        "comments_count": 35,
        "public_reactions_count": 35,
        "collection_id": null,
        "published_timestamp": "2025-01-10T05:00:00Z",
        "language": "en",
        "subforem_id": 1,
        "positive_reactions_count": 35,
        "cover_image": "https://media2.dev.to/dynamic/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fs93hbpvn2a4vrq3wcy2f.jpg",
        "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fs93hbpvn2a4vrq3wcy2f.jpg",
        "canonical_url": "https://dev.to/devteam/what-was-your-win-this-week-5j6",
        "created_at": "2025-01-08T19:40:54Z",
        "edited_at": "2025-01-08T20:06:58Z",
        "crossposted_at": null,
        "published_at": "2025-01-10T05:00:00Z",
        "last_comment_at": "2025-01-25T02:33:21Z",
        "reading_time_minutes": 1,
        "tag_list": [
            "weeklyretro",
            "discuss"
        ],
        "tags": "weeklyretro, discuss",
        "user": {
            "name": "Jess Lee",
            "username": "jess",
            "twitter_username": "jessleenyc",
            "github_username": "jessleenyc",
            "user_id": 264,
            "website_url": null,
            "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F264%2F40d89fb9-4de0-414d-8a06-f52ddda0bc75.jpg",
            "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F264%2F40d89fb9-4de0-414d-8a06-f52ddda0bc75.jpg"
        },
        "organization": {
            "name": "The DEV Team",
            "username": "devteam",
            "slug": "devteam",
            "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F1%2Fd908a186-5651-4a5a-9f76-15200bc6801f.jpg",
            "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Forganization%2Fprofile_image%2F1%2Fd908a186-5651-4a5a-9f76-15200bc6801f.jpg"
        },
        "flare_tag": {
            "name": "discuss",
            "bg_color_hex": "#71EA8B",
            "text_color_hex": "#FFFFFF"
        }
    }
]